# Generated by Django 6.1.1 on 2026-09-19 16:31

import iiif_ocr_web.ocr.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('invalid', 'Invalid')], default='available', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False)),
                ('language', models.CharField(choices=[('abq', 'Abaza'), ('af', 'Afrikaans'), ('ang', 'Old English'), ('ar', 'Arabic'), ('ava', 'Avaric'), ('az', 'Azerbaijani'), ('be', 'Belarusian'), ('bg', 'Bulgarian'), ('bgc', 'Haryanvi'), ('bh', 'Bihari'), ('bho', 'Bhojpuri'), ('bs', 'Bosnian'), ('ch', 'Chinese (Simplified)'), ('che', 'Chechen'), ('chinese_cht', 'Chinese (Traditional)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('dar', 'Dargwa'), ('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('et', 'Estonian'), ('fa', 'Persian'), ('fr', 'French'), ('ga', 'Irish'), ('gom', 'Konkani'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('inh', 'Ingush'), ('is', 'Icelandic'), ('it', 'Italian'), ('japan', 'Japanese'), ('ka', 'Georgian'), ('kbd', 'Kabardian'), ('korean', 'Korean'), ('ku', 'Kurdish'), ('la', 'Latin'), ('lbe', 'Lak'), ('lez', 'Lezghian'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mah', 'Magahi'), ('mai', 'Maithili'), ('mi', 'Maori'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('mt', 'Maltese'), ('ne', 'Nepali'), ('new', 'Newari'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('oc', 'Occitan'), ('pi', 'Pali'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('rs_cyrillic', 'Serbian (Cyrillic)'), ('rs_latin', 'Serbian (Latin)'), ('ru', 'Russian'), ('sa', 'Sanskrit'), ('sck', 'Sadri'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('tab', 'Tabassaran'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tl', 'Tagalog'), ('tr', 'Turkish'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese')], default='en', max_length=20)),
                ('image_size', models.PositiveSmallIntegerField(choices=[(625, 'Small'), (1250, 'Medium'), (2500, 'Large')], default=1250)),
                ('visualize', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_page', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ocr.manifest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('manifest', 'number'), name='unique_manifest_job_number')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('source_url', models.URLField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('hocr', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('source_image', models.FileField(blank=True, upload_to=iiif_ocr_web.ocr.models.ocr_upload_path)),
                ('ocr_visualization', models.FileField(blank=True, upload_to=iiif_ocr_web.ocr.models.ocr_upload_path)),
                ('layout_visualization', models.FileField(blank=True, upload_to=iiif_ocr_web.ocr.models.ocr_upload_path)),
                ('bboxes_visualization', models.FileField(blank=True, upload_to=iiif_ocr_web.ocr.models.ocr_upload_path)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr.ocrjob')),
            ],
            options={
                'ordering': ['job', 'page_number'],
                'constraints': [models.UniqueConstraint(fields=('job', 'page_number'), name='unique_job_page_number')],
            },
        ),
    ]
